# Generated by Django 4.2.13 on 2026-04-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_document', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
